---
# tasks/Amazon/main.yml: CentOS specific set-up
# This takes care of base prerequisites for Amazon Linux AMI

- include_vars: "{{ ansible_distribution }}.yml"
  tags: setup

- name: Set epel_version override when AmazonLinux AMIv2
  tags: setup
  set_fact:
    epel_version: 7
  when: ansible_distribution_version == 'Candidate'

- name: Ensure the Sensu Core Yum repo is present
  tags: setup
  yum_repository:
    name: sensu
    description: The Sensu Core yum repository
    baseurl: "{{ sensu_yum_repo_url }}"
    gpgkey: "{{ sensu_yum_key_url }}"
    gpgcheck: yes
    enabled: yes

- name: Ensure Sensu is installed
  tags: setup
  yum:
    name: "{{ sensu_package }}"
    state: "{{ sensu_pkg_state }}"
