---
# tasks/client.yml: Deploy various client-side configurations for Sensu

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Deploy Sensu client service configuration
    template:
      dest: "{{ sensu_config_path }}/conf.d/client.json"
      owner: "{{ sensu_user_name }}"
      group: "{{ sensu_group_name }}"
      src: "{{ sensu_client_config  }}"
    notify: restart sensu-client service

  - include: SmartOS/client.yml
    when: ansible_distribution == "SmartOS"
    static: false

  - name: Ensure Sensu client service is running
    service: name=sensu-client state=started enabled=yes
