---
# tasks/ssl.yml: Deploy the client SSL cert/key to client systems

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure Sensu SSL directory exists
    file:
      dest: "{{ sensu_config_path }}/ssl"
      state: directory
      owner: "{{ sensu_user_name }}"
      group: "{{ sensu_group_name }}"

  - include: ssl_generate.yml
    when: sensu_ssl_gen_certs

  - name: Deploy the Sensu client SSL cert/key
    copy:
      src: "{{ item }}"
      owner: "{{ sensu_user_name }}"
      remote_src: "{{ sensu_ssl_deploy_remote_src }}"
      group: "{{ sensu_group_name }}"
      dest: "{{ sensu_config_path }}/ssl"
    with_items:
      - "{{ sensu_ssl_client_cert }}"
      - "{{ sensu_ssl_client_key }}"
    notify: restart sensu-client service
