---
# tasks/FreeBSD/main.yml: FreeBSD specific set-up
# This takes care of base prerequisites for FreeBSD

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Set sensu_pkg_version {{ ansible_distribution }} override
    set_fact:
      sensu_pkg_version: "{{ sensu_pkg_version }}"
    when: sensu_pkg_version is none

  - name: Ensure the Sensu group is present
    group: name={{ sensu_group_name }} state=present

  - name: Ensure the Sensu user is present
    user:
      name: "{{ sensu_user_name }}"
      group: "{{ sensu_group_name }}"
      shell: /bin/false
      home: "{{ sensu_config_path }}"
      createhome: true
      state: present

  - name: Create pkgng custom repo config directory
    file:
      path: /usr/local/etc/pkg/repos/
      state: directory

  - name: Install sensu repo
    template:
      src: sensu-freebsd-repo.conf.j2
      dest: /usr/local/etc/pkg/repos/sensu.conf
    notify:
      - Update pkgng database

  - name: Install prerequisite packages
    pkgng:
      name: "{{ item }}"
      state: present
    with_items:
      - bash
      - ca_root_nss

  - name: Install sensu
    pkgng:
      name: "sensu{% if sensu_pkg_version %}-{{ sensu_pkg_version }}{% endif %}"
      state: present
