---
# tasks/Debian/main.yml: Debian specific set-up
# This takes care of base prerequisites for Debian

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure apt-transport-https is installed
    apt:
      name: apt-transport-https
      state: present
      cache_valid_time: 3600
      update_cache: true

  - name: Ensure that gnupg is installed for apt_key
    apt:
      name: gnupg
      state: present

  - name: Ensure the Sensu APT repo GPG key is present
    apt_key:
      url: "{{ sensu_apt_key_url }}"
      state: present

  - name: Ensure the Sensu Core APT repo is present
    apt_repository:
      repo: "{{ sensu_apt_repo_url }}"
      state: present
      update_cache: true

  - name: Ensure Sensu is installed
    apt:
      name: "{{ sensu_package }}"
      state: "{{ sensu_pkg_state }}"
