---
# tasks/Debian/rabbit.yml: Deploy RabbitMQ
# Specific to Debian

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure the RabbitMQ APT repo GPG key is present
    apt_key:
      url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
      state: present

  - name: Ensure the RabbitMQ APT repo is present
    apt_repository:
      repo: "deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main"
      filename: rabbitmq
      state: present
      update_cache: true

  - name: Ensure the Erlang APT repo GPG key is present
    apt_key:
      url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
      state: present

  - name: Ensure the Erlang APT repo is present
    apt_repository:
      repo: "deb https://packages.erlang-solutions.com/debian {{ ansible_distribution_release }} contrib"
      filename: erlang
      state: present
      update_cache: true

  - name: Ensure RabbitMQ is installed
    apt:
      name: rabbitmq-server
      state: "{{ sensu_rabbitmq_pkg_state }}"
      cache_valid_time: 600
      update_cache: true
