---
# tasks/Debian/rabbit.yml: Deploy RabbitMQ
# Specific to Debian

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure the RabbitMQ APT repo GPG key is present
    apt_key:
      url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
      state: present

  - name: Ensure the RabbitMQ APT repo is present
    apt_repository:
      repo: 'deb http://www.rabbitmq.com/debian/ testing main'
      state: present
      update_cache: true

  - name: Ensure RabbitMQ is installed
    apt:
      name: rabbitmq-server
      state: "{{ rabbitmq_pkg_state }}"
      update_cache: true
