---
# tasks/Debian/redis.yml: Deploy redis
# Specific to Debian

- name: Include ansible_distribution vars
  include_vars:
    file: "{{ ansible_distribution }}.yml"
  tags: redis

- name: Ensure redis is installed
  tags: redis
  apt:
    name: "{{ redis_pkg_name }}"
    state: "{{ redis_pkg_state }}"
    update_cache: true

- name: Ensure redis binds to accessible IP
  tags: redis
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: '^bind'
    line: 'bind 0.0.0.0'
  notify: restart redis service

- meta: flush_handlers
  tags: redis
