---
# tasks/Ubuntu/main.yml: Ubuntu specific set-up
# This takes care of base prerequisites for Ubuntu

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure that https transport is ready
    apt: name=apt-transport-https state=present
    
  - name: Ensure the Sensu APT repo GPG key is present
    apt_key:
      url: https://sensu.global.ssl.fastly.net/apt/pubkey.gpg
      state: present

  - name: Ensure the Sensu Core APT repo is present
    apt_repository:
      repo: "deb     https://sensu.global.ssl.fastly.net/apt {{ ansible_distribution_release }} main"
      state: present
      update_cache: true

  - name: Ensure Sensu is installed
    apt: name={{ sensu_package }} state={{ sensu_pkg_state }}
