---
# tasks/Ubuntu/rabbit.yml: Deploy RabbitMQ
# Specific to Ubuntu

- include_vars: "{{ ansible_distribution }}.yml"

- name: Ensure the RabbitMQ APT repo GPG key is present
  apt_key:
    url: "{{ sensu_rabbitmq_signing_key }}"
    state: present

- name: Ensure the RabbitMQ APT repo is present
  apt_repository:
    repo: "{{ sensu_rabbitmq_repo }}"
    filename: rabbitmq
    state: present
    update_cache: true

- name: Ensure the Erlang APT repo GPG key is present
  apt_key:
    url: "{{ sensu_rabbitmq_erlang_signing_key }}"
    state: present

- name: Ensure the Erlang APT repo is present
  apt_repository:
    repo: "{{ sensu_rabbitmq_erlang_repo }}"
    filename: erlang
    state: present
    update_cache: true

- name: Ensure RabbitMQ is installed
  apt:
    name: rabbitmq-server
    state: "{{ rabbitmq_pkg_state }}"
    cache_valid_time: 600
    update_cache: true
