---
# tasks/Ubuntu/redis.yml: Deploy redis
# Specific to Ubuntu

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure redis is installed
    apt:
      name: "{{ sensu_redis_pkg_name }}"
      state: "{{ sensu_redis_pkg_state }}"
      update_cache: true

  - name: Ensure redis binds to accessible IP
    lineinfile:
      dest: /etc/redis/redis.conf
      regexp: '^bind'
      line: 'bind 0.0.0.0'
    notify: restart redis service

  - meta: flush_handlers
