---
# tasks/SmartOS/client.yml: Deploy various client-side configurations for Sensu
# Specific to Joyent SmartOS

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Deploy Sensu client service manifest
    template:
      dest: /opt/local/lib/svc/manifest/sensu-client.xml
      src: sensu-client.smartos_smf_manifest.xml.j2
      owner: root
      group: root
      mode: 0644
    notify:
      - import sensu-client service
      - restart sensu-client service

  - meta: flush_handlers
