---
# tasks/SmartOS/redis.yml: Deploy redis
# Specific to Ubuntu

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure redis is installed
    pkgin: name=redis state={{ sensu_redis_pkg_state }}
