---
# tasks/CentOS/redis.yml: Deploy redis
# Specific to CentOS

- name: Include ansible_distribution vars
  include_vars:
    file: "{{ ansible_distribution }}.yml"
  tags: redis

- name: Install EPEL repo
  tags: redis
  yum:
    name: epel-release
    state: present
  when: enable_epel_repo

- name: Ensure redis is installed
  tags: redis
  yum:
    name: "{{ sensu_redis_pkg_name }}"
    state: "{{ sensu_redis_pkg_state }}"
    enablerepo: "{{ centos_repository }}"

- name: Ensure redis binds to accessible IP
  tags: redis
  lineinfile:
    dest: /etc/redis.conf
    regexp: '^bind'
    line: 'bind 0.0.0.0'
